name: Ubuntu (Laravel 12, PHP 8.3)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    # right now, ubuntu-latest has explicit PHP 8.3 support
    # see https://github.com/marketplace/actions/setup-php-action
    # specify PHP 8.3 to test Laravel 12
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # - name: Setup PHP with PECL extension
    #   uses: shivammathur/setup-php@v2
    #   with:
    #     php-version: '8.3'

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # dump autoload to "boot" our custom mock artisan
    - name: Dump auto-load details
      run: composer dump-autoload

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run test suite
      run: composer run-script test
