name: PHP Composer (Ubuntu; Laravel 11)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    # no ubuntu runner has explicit PHP 8.2 support
    # see https://github.com/marketplace/actions/setup-php-action
    # specify PHP 8.2 to test Laravel 11
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # dump autoload to "boot" our custom mock artisan
    - name: Dump auto-load details
      run: composer dump-autoload

    - name: Sanity Check
      run: timeout 1 php artisan async:run Tzo0MzoiVmVjdG9yaWFsMTAyNFxMYXJhdmVsUHJvY2Vzc0FzeW5jXEFzeW5jVGFzayI6NTp7czo1MjoiAFZlY3RvcmlhbDEwMjRcTGFyYXZlbFByb2Nlc3NBc3luY1xBc3luY1Rhc2sAdGhlVGFzayI7Tzo2MToiVmVjdG9yaWFsMTAyNFxMYXJhdmVsUHJvY2Vzc0FzeW5jXFRlc3RzXFRlc3RUaW1lb3V0Tm9ybWFsVGFzayI6Mjp7czo3MDoiAFZlY3RvcmlhbDEwMjRcTGFyYXZlbFByb2Nlc3NBc3luY1xUZXN0c1xUZXN0VGltZW91dE5vcm1hbFRhc2sAbWVzc2FnZSI7czoxNToidGltZW91dCBvY2N1cmVkIjtzOjc3OiIAVmVjdG9yaWFsMTAyNFxMYXJhdmVsUHJvY2Vzc0FzeW5jXFRlc3RzXFRlc3RUaW1lb3V0Tm9ybWFsVGFzawB0YXJnZXRGaWxlUGF0aCI7czo2MzoiL2hvbWUvd3l3b25nL2xhcmF2ZWwtcHJvY2Vzcy1hc3luYy9zdG9yYWdlL3Rlc3RBc3luY1RpbWVvdXQudHh0Ijt9czo1ODoiAFZlY3RvcmlhbDEwMjRcTGFyYXZlbFByb2Nlc3NBc3luY1xBc3luY1Rhc2sAcnVubmVyUHJvY2VzcyI7TjtzOjU0OiIAVmVjdG9yaWFsMTAyNFxMYXJhdmVsUHJvY2Vzc0FzeW5jXEFzeW5jVGFzawB0aW1lTGltaXQiO2k6MTtzOjYwOiIAVmVjdG9yaWFsMTAyNFxMYXJhdmVsUHJvY2Vzc0FzeW5jXEFzeW5jVGFzawBsYXJhdmVsU3RhcnRWYWwiO047czo1NjoiAFZlY3RvcmlhbDEwMjRcTGFyYXZlbFByb2Nlc3NBc3luY1xBc3luY1Rhc2sAdGltZXJQcm9jSUQiO2k6MDt9

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run test suite
      run: composer run-script test
